apiVersion: v1
kind: Pod
metadata:
  annotations:
    dag_id: spark_pi
    execution_date: "2021-05-09T12:27:00.213132+00:00"
    kubernetes.io/psp: eks.privileged
    task_id: spark_pi_submit
    try_number: "10"
  labels:
    airflow-worker: "2"
    airflow_version: 2.0.2
    dag_id: spark_pi
    execution_date: 2021-05-09T12_27_00.213132_plus_00_00
    kubernetes_executor: "True"
    task_id: spark_pi_submit
    try_number: "1"
  name: sparkpisparkpisubmit.b4fc6cd152c74dc4b4d336888f59a508
  namespace: airflow
spec:
  affinity: {}
  containers:
  - args:
    - airflow
    - tasks
    - run
    - spark_pi
    - spark_pi_submit
    - "2021-05-09T12:27:00.213132+00:00"
    - --local
    - --pool
    - default_pool
    - --subdir
    - /opt/airflow/dags/repo/spark_k8s_operator_spark_pi.py
    env:
    - name: AIRFLOW__CORE__EXECUTOR
      value: LocalExecutor
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          key: fernet-key
          name: airflow-fernet-key
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-metadata
    - name: AIRFLOW_CONN_AIRFLOW_DB
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-metadata
    - name: AIRFLOW_IS_K8S_EXECUTOR_POD
      value: "True"
    image: apache/airflow:2.0.2-python3.8
    imagePullPolicy: IfNotPresent
    name: base
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/airflow/logs
      name: airflow-logs
    - mountPath: /opt/airflow/airflow.cfg
      name: config
      readOnly: true
      subPath: airflow.cfg
    - mountPath: /opt/airflow/dags/repo/
      name: dags
      readOnly: true
      subPath: repo/
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: airflow-worker-token-28jk2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: GIT_SYNC_REV
      value: HEAD
    - name: GIT_SYNC_BRANCH
      value: main
    - name: GIT_SYNC_REPO
      value: https://github.com/alextarasov-spot/dags.git
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_ROOT
      value: /git
    - name: GIT_SYNC_DEST
      value: repo
    - name: GIT_SYNC_ADD_USER
      value: "true"
    - name: GIT_SYNC_WAIT
      value: "60"
    - name: GIT_SYNC_MAX_SYNC_FAILURES
      value: "0"
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    image: k8s.gcr.io/git-sync:v3.1.6
    imagePullPolicy: IfNotPresent
    name: git-sync
    resources: {}
    securityContext:
      runAsUser: 65533
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /git
      name: dags
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: airflow-worker-token-28jk2
      readOnly: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
    runAsUser: 50000
  serviceAccount: airflow-worker
  serviceAccountName: airflow-worker
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: dags
  - emptyDir: {}
    name: airflow-logs
  - configMap:
      defaultMode: 420
      name: airflow-airflow-config
    name: config
  - name: airflow-worker-token-28jk2
    secret:
      defaultMode: 420
      secretName: airflow-worker-token-28jk2